### ISSUE TITLE
Object not found / Error 404

### ISSUE THREAD

**Issue by baarthur** [rCarto/flow#4]
Hi, 

I'm having this issue when trying to open the package's vignette [free translation from Portuguese, actual message might be slightly different in English]:

"Object not found!
The requested URL was not found on this server. The link in the referred page seems to be with an error or outdated. Please inform this page's author about this error.

If you believe to have found a server error, please contact the webmaster.

Error 404
cran.r-project.org
Apache"

Also, could not install the package on R:
`install.packages("flows")
Installing package into ‘C:/(...)/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘flows’ is not available for this version of R

A version of this package for your version of R might be available elsewhere`

I'm having the same problem with stplanr, though other packages work fine.

**Comment by rCarto** [comment]
Hello, 
`flows` is not on the CRAN anymore. I'm working on putting it back. 
For now, you can install the github version with `remotes::install_github("rCarto/flows")`
